### PR TITLE
Fix uo

### PR DESCRIPTION
**Pull request by Georgi87**
A fix for the front running issue in the UO discovered by @niran

(For some reason I cannot add you as reviewer @niran. I guess because you are not part of the Gnosis organization?)

### CODE REVIEW

**Comment by cag** [comment]
Okay, so `(totalAmount - totalOutcomeAmounts[_outcome]).mul(spreadMultiplier)` could be less than `totalOutcomeAmounts[_outcome]` if somebody was already voting for an outcome which is far enough in the lead, like if somebody voted for the challenge outcome immediately after the outcome was set. In that case, the oracle would reject the transaction instead of doing a 0 transaction, which is what would happen if a person over-committed to a vote. However, these seem to be analogous situations to me.

I recommend adding a test section under the challenge:

```javascript
        // Sender 1 tries to increase their bid but can't
        await etherToken.deposit({value: 50, from: accounts[sender1]})
        await etherToken.approve(ultimateOracle.address, 50, { from: accounts[sender1] })
        await ultimateOracle.voteForOutcome(2, 50, { from: accounts[sender1] })
        assert.equal(await ultimateOracle.outcomeAmounts(accounts[sender1], 2), 100)
```

And clamping the subtraction so the maxAmount gets set to 0 when the subtraction would underflow.

**Comment by niran** [comment]
Looks good to me!

**Comment by Georgi87** [comment]
Thank you both for checking, I will add the test.

**Comment by Georgi87** [comment]
Added a test for this @cag 

The transaction thorws, because the .sub method throws.

**Pull request merged**
