### PR TITLE
One repo

### PR DESCRIPTION
**Pull request by cag**
... to rule them all, and in the dankness, bind them.

lol

### CODE REVIEW

**Comment by Georgi87** [comment]
Cool, looks good thanks!

Should we keep the unfinished truffle test in the repo? The test is dulicated.

**Comment by cag** [comment]
Up to you. It is probably okay to leave as is. All tests are passing now anyway. I think @collinc97 is working on some tests, and I had planned to have them brought over when they were done, but the changeset should be just a drop-in thing.

**Comment by Georgi87** [comment]
Alright, lets keep it as it is. Just one thing: The requirements.txt should be updated and unused modules should be removed. Are the tests compatible with the current pyethereum version?

**Comment by cag** [comment]
No, and it is not trivial to port it. I think the requirements should be looked at, as the new version should support the tests... _with some code changes_

**Comment by Georgi87** [comment]
Ok, that should be a separate PR then.

**Pull request merged**
